-- Full 50-task curated seed corpus (Phase 1.4): 10 per suite, spanning
-- all 5 scoring types, replacing the 6-task placeholder set from 0005.
delete from benchmark_tasks where authored_by is null;

insert into benchmark_tasks (suite, category, type, title, description, input, expected_output, rubric, test_cases, difficulty)
values
  ($$codearena$$, $$algorithms$$, $$exact$$, $$Count set bits in an integer's binary form$$, $$Given an integer n, return the number of 1-bits in its binary representation, as a string.$$, $${"n": 29}$$::jsonb, $$"4"$$::jsonb, null, null, $$easy$$),
  ($$codearena$$, $$algorithms$$, $$exact$$, $$Determine the return value of a recursive function$$, $$Given the Python function below and a call, determine what it returns.

def f(n):
    if n <= 1:
        return n
    return f(n-1) + 2*f(n-2)

What does f(10) return?$$, $${"code": "def f(n):\n    if n <= 1:\n        return n\n    return f(n-1) + 2*f(n-2)\n", "call": "f(10)"}$$::jsonb, $$"341"$$::jsonb, null, null, $$medium$$),
  ($$codearena$$, $$orchestration$$, $$structural$$, $$Lint, format, then test a Python module$$, $$Given a Python file, run the linter, then the formatter, then the test suite, in that order.$$, $${"file": "utils.py", "steps": ["lint", "format", "test"]}$$::jsonb, $${"tool_calls": ["lint", "format", "test"]}$$::jsonb, null, null, $$medium$$),
  ($$codearena$$, $$debugging$$, $$functional$$, $$Fix a broken IBAN validator$$, $$The function below validates IBAN numbers but has a bug in the checksum step. Fix it so all test cases pass.$$, $${"code": "def validate_iban(iban):\n    iban = iban.replace(' ', '').upper()\n    rearranged = iban[4:] + iban[:4]\n    digits = ''\n    for ch in rearranged:\n        if ch.isdigit():\n            digits += ch\n        else:\n            digits += str(ord(ch) - ord('A') + 10)\n    return int(digits) % 97 == 0\n"}$$::jsonb, null, null, $$[{"input": "GB82WEST12345698765432", "expected": true}, {"input": "GB82WEST12345698765431", "expected": false}, {"input": "DE89370400440532013000", "expected": true}]$$::jsonb, $$medium$$),
  ($$codearena$$, $$debugging$$, $$functional$$, $$Repair a stack-based balanced-brackets checker$$, $$The function below checks whether brackets are balanced but has a bug that lets mismatched pairs pass. Fix it.$$, $${"code": "def is_balanced(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for ch in s:\n        if ch in '([{':\n            stack.append(ch)\n        elif ch in ')]}':\n            if not stack:\n                return False\n            top = stack.pop()\n            if top != ch:\n                return False\n    return len(stack) == 0\n"}$$::jsonb, null, null, $$[{"input": "()[]{}", "expected": true}, {"input": "(]", "expected": false}, {"input": "([{}])", "expected": true}, {"input": "(", "expected": false}]$$::jsonb, $$easy$$),
  ($$codearena$$, $$debugging$$, $$functional$$, $$Correct an off-by-one in a sliding-window maximum-sum function$$, $$The function below should return the maximum sum of any window of size k, but has an off-by-one bug. Fix it.$$, $${"code": "def max_window_sum(nums, k):\n    n = len(nums)\n    if k > n:\n        return None\n    window_sum = sum(nums[:k])\n    best = window_sum\n    for i in range(k, n):\n        window_sum += nums[i] - nums[i - k - 1]\n        best = max(best, window_sum)\n    return best\n"}$$::jsonb, null, null, $$[{"input": {"nums": [2, 1, 5, 1, 3, 2], "k": 3}, "expected": 9}, {"input": {"nums": [1, 1, 1, 1, 1], "k": 2}, "expected": 2}]$$::jsonb, $$medium$$),
  ($$codearena$$, $$debugging$$, $$functional$$, $$Fix a broken quicksort partition step$$, $$The quicksort implementation below sorts incorrectly due to an inverted comparison in the partition step. Fix it.$$, $${"code": "def partition(arr, low, high):\n    pivot = arr[high]\n    i = low - 1\n    for j in range(low, high):\n        if arr[j] >= pivot:\n            i += 1\n            arr[i], arr[j] = arr[j], arr[i]\n    arr[i + 1], arr[high] = arr[high], arr[i + 1]\n    return i + 1\n\ndef quicksort(arr, low=0, high=None):\n    if high is None:\n        high = len(arr) - 1\n    if low < high:\n        p = partition(arr, low, high)\n        quicksort(arr, low, p - 1)\n        quicksort(arr, p + 1, high)\n    return arr\n"}$$::jsonb, null, null, $$[{"input": [5, 2, 9, 1, 5, 6], "expected": [1, 2, 5, 5, 6, 9]}, {"input": [3, 3, 3], "expected": [3, 3, 3]}, {"input": [], "expected": []}]$$::jsonb, $$medium$$),
  ($$codearena$$, $$debugging$$, $$functional$$, $$Fix a broken doubly linked list node removal$$, $$Removing a node from this doubly linked list corrupts the backward links. Given a list of values and an index to remove, fix the removal so a forward traversal after removal is correct.$$, $${"code": "class Node:\n    def __init__(self, val):\n        self.val = val\n        self.prev = None\n        self.next = None\n\ndef remove_node(node):\n    if node.prev:\n        node.prev.next = node.next\n    if node.next:\n        node.next.prev = node.next\n"}$$::jsonb, null, null, $$[{"input": {"values": [1, 2, 3, 4], "remove_index": 1}, "expected": [1, 3, 4]}, {"input": {"values": [1, 2, 3], "remove_index": 0}, "expected": [2, 3]}]$$::jsonb, $$medium$$),
  ($$codearena$$, $$debugging$$, $$functional$$, $$Fix a broken nested-dict flattening function$$, $$This function should flatten a nested dict using a caller-supplied separator, but ignores the separator on recursive calls. Fix it.$$, $${"code": "def flatten(d, parent_key='', sep='.'):\n    items = {}\n    for k, v in d.items():\n        new_key = f'{parent_key}{sep}{k}' if parent_key else k\n        if isinstance(v, dict):\n            items.update(flatten(v, new_key, sep='_'))\n        else:\n            items[new_key] = v\n    return items\n"}$$::jsonb, null, null, $$[{"input": {"d": {"a": {"b": 1, "c": {"d": 2}}}, "sep": "."}, "expected": {"a.b": 1, "a.c.d": 2}}]$$::jsonb, $$medium$$),
  ($$codearena$$, $$debugging$$, $$functional$$, $$Fix a broken LRU cache eviction order$$, $$This LRU cache evicts the wrong key because get() does not mark a key as recently used. Fix it so eviction order is correct.$$, $${"code": "from collections import OrderedDict\n\nclass LRUCache:\n    def __init__(self, capacity):\n        self.capacity = capacity\n        self.cache = OrderedDict()\n\n    def get(self, key):\n        if key not in self.cache:\n            return -1\n        value = self.cache[key]\n        return value\n\n    def put(self, key, value):\n        if key in self.cache:\n            del self.cache[key]\n        elif len(self.cache) >= self.capacity:\n            self.cache.popitem(last=False)\n        self.cache[key] = value\n"}$$::jsonb, null, null, $$[{"input": {"capacity": 2, "ops": [["put", 1, 1], ["put", 2, 2], ["get", 1], ["put", 3, 3], ["get", 2]]}, "expected": [null, null, 1, null, -1]}]$$::jsonb, $$hard$$),
  ($$researchbench$$, $$data-processing$$, $$exact$$, $$Convert a duration string to total seconds$$, $$Given a duration string like '2h45m30s', compute the total number of seconds it represents.$$, $${"duration": "2h45m30s"}$$::jsonb, $$"9930"$$::jsonb, null, null, $$easy$$),
  ($$researchbench$$, $$data-processing$$, $$exact$$, $$Compute a UPC-A barcode check digit$$, $$Given the first 11 digits of a UPC-A barcode, compute the 12th check digit using the standard UPC-A algorithm.$$, $${"digits": "03600029145"}$$::jsonb, $$"2"$$::jsonb, null, null, $$medium$$),
  ($$researchbench$$, $$orchestration$$, $$structural$$, $$Fetch a paper's abstract, then extract its citation count$$, $$Given a paper identifier, first fetch its abstract, then extract its citation count from the fetched metadata.$$, $${"paper_id": "arxiv:2307.09288", "steps": ["fetch_abstract", "extract_citations"]}$$::jsonb, $${"tool_calls": ["fetch_abstract", "extract_citations"]}$$::jsonb, null, null, $$medium$$),
  ($$researchbench$$, $$synthesis$$, $$semantic$$, $$Summarize the largest DeFi hacks of 2025$$, $$Research and summarize the three largest DeFi protocol hacks in 2025 by dollar value, including protocol name, amount lost, and root cause.$$, $${"prompt": "List the 3 largest DeFi hacks of 2025 with amount lost and root cause."}$$::jsonb, null, $$Award full credit if the response names 3 real, correctly-ordered DeFi incidents with plausible dollar amounts and a specific root cause (not a vague 'exploit'). Deduct credit for fabricated incidents or a missing root cause.$$, null, $$hard$$),
  ($$researchbench$$, $$synthesis$$, $$semantic$$, $$Compare three vector database options for a production RAG pipeline$$, $$Compare three real vector database products on at least two concrete technical dimensions relevant to a production RAG deployment.$$, $${"prompt": "Compare 3 vector databases for a production RAG pipeline."}$$::jsonb, null, $$Full credit requires naming 3 real, distinct vector databases (e.g. Pinecone, Weaviate, Qdrant, Milvus, pgvector) and comparing them on at least 2 concrete dimensions (e.g. latency, hybrid search support, managed vs self-hosted, cost). Deduct credit for vague comparisons with no concrete differentiators or fabricated products.$$, null, $$medium$$),
  ($$researchbench$$, $$synthesis$$, $$semantic$$, $$Explain the tradeoffs between RAG and fine-tuning for domain adaptation$$, $$Explain when retrieval-augmented generation is preferable to fine-tuning for adapting an LLM to a domain, and vice versa.$$, $${"prompt": "RAG vs fine-tuning for domain adaptation: tradeoffs?"}$$::jsonb, null, $$Full credit requires at least 2 tradeoffs on each side (e.g. RAG: fresher data, no retraining cost, retrieval latency, context window limits; fine-tuning: baked-in knowledge, higher upfront cost, staleness). Deduct credit for one-sided or generic answers.$$, null, $$medium$$),
  ($$researchbench$$, $$synthesis$$, $$semantic$$, $$Synthesize recent techniques for extending LLM context windows$$, $$Name and briefly explain at least two distinct techniques used to extend LLM context window length.$$, $${"prompt": "What techniques extend LLM context windows, and how do they work?"}$$::jsonb, null, $$Full credit if the response names at least 2 concrete techniques (e.g. RoPE scaling, sliding window attention, sparse attention, retrieval augmentation) with a brief correct explanation of the mechanism. Deduct credit for hand-wavy answers with no named technique.$$, null, $$hard$$),
  ($$researchbench$$, $$synthesis$$, $$semantic$$, $$Explain the key difference between Constitutional AI and standard RLHF$$, $$Explain the core mechanism that distinguishes Constitutional AI from standard RLHF.$$, $${"prompt": "What is the key difference between Constitutional AI and RLHF?"}$$::jsonb, null, $$Full credit if the response correctly notes that Constitutional AI uses AI-generated feedback against a written set of principles (self-critique and revision) to reduce reliance on human preference labels, versus RLHF's direct human-labeled preference data. Deduct credit for conflating the two or vague answers.$$, null, $$medium$$),
  ($$researchbench$$, $$synthesis$$, $$semantic$$, $$Research current approaches to AI agent benchmarking$$, $$Name at least two real AI agent benchmarks or approaches, and identify a real limitation shared by static benchmarks.$$, $${"prompt": "What approaches exist for benchmarking AI agents, and what are static benchmarks' limitations?"}$$::jsonb, null, $$Full credit if the response identifies at least 2 named benchmarks or approaches (e.g. GAIA, SWE-bench, WebArena, AgentBench) and notes a real limitation of static benchmarks (e.g. staleness, no verification, no community input). Deduct credit for generic answers with no named benchmark.$$, null, $$hard$$),
  ($$researchbench$$, $$synthesis$$, $$semantic$$, $$Explain why sparse mixture-of-experts models reduce inference cost$$, $$Explain why sparse mixture-of-experts architectures reduce inference compute without reducing total parameter count.$$, $${"prompt": "Why does sparse MoE reduce inference cost without reducing total parameters?"}$$::jsonb, null, $$Full credit if the response correctly explains that only a subset of experts (selected by a router/gating function) are activated per token, so compute scales with active parameters, not total parameters. Deduct credit for answers that confuse this with quantization, distillation, or pruning.$$, null, $$hard$$),
  ($$tooluse$$, $$reasoning$$, $$exact$$, $$Determine which of two API rate limits is more restrictive$$, $$Given two API rate limits expressed as requests per time window, determine which one permits fewer requests per second.$$, $${"limit_a": {"requests": 100, "per_seconds": 60}, "limit_b": {"requests": 1000, "per_seconds": 3600}}$$::jsonb, $$"limit_b"$$::jsonb, null, null, $$medium$$),
  ($$tooluse$$, $$reasoning$$, $$exact$$, $$Compute the number of requests allowed in a fixed burst window$$, $$Given a steady request rate and a burst window length, compute the total requests allowed in that window.$$, $${"rate_per_second": 5, "burst_window_seconds": 12}$$::jsonb, $$"60"$$::jsonb, null, null, $$easy$$),
  ($$tooluse$$, $$orchestration$$, $$structural$$, $$Summarize a file, then translate the summary to Spanish$$, $$Given a text file, call the summarize tool first, then call the translate tool on the summary output with target language 'es'.$$, $${"file": "quarterly_report.txt", "steps": ["summarize", "translate"]}$$::jsonb, $${"tool_calls": ["summarize", "translate"]}$$::jsonb, null, null, $$medium$$),
  ($$tooluse$$, $$orchestration$$, $$structural$$, $$Query active user count, then post the result to Slack$$, $$Query the database for the active user count, then post the result to a Slack channel.$$, $${"query": "SELECT COUNT(*) FROM users WHERE active = true", "steps": ["query_db", "post_slack"]}$$::jsonb, $${"tool_calls": ["query_db", "post_slack"]}$$::jsonb, null, null, $$medium$$),
  ($$tooluse$$, $$orchestration$$, $$structural$$, $$Look up a stock's current price, then compute percent change from yesterday's close$$, $$Get the current quote for a ticker, then compute the percent change from yesterday's closing price.$$, $${"ticker": "NVDA", "steps": ["get_quote", "compute_pct_change"]}$$::jsonb, $${"tool_calls": ["get_quote", "compute_pct_change"]}$$::jsonb, null, null, $$medium$$),
  ($$tooluse$$, $$orchestration$$, $$structural$$, $$Read a CSV, filter rows by a condition, then write the filtered rows to a new file$$, $$Read the given CSV, filter rows matching the condition, then write the filtered rows to a new file.$$, $${"file": "orders.csv", "filter": "status == 'shipped'", "steps": ["read_csv", "filter_rows", "write_csv"]}$$::jsonb, $${"tool_calls": ["read_csv", "filter_rows", "write_csv"]}$$::jsonb, null, null, $$medium$$),
  ($$tooluse$$, $$orchestration$$, $$structural$$, $$Look up a user's timezone, then schedule a reminder in their local time$$, $$Look up the user's timezone, then schedule the reminder converted to their local time.$$, $${"user_id": "u_492", "steps": ["get_timezone", "schedule_reminder"]}$$::jsonb, $${"tool_calls": ["get_timezone", "schedule_reminder"]}$$::jsonb, null, null, $$medium$$),
  ($$tooluse$$, $$debugging$$, $$functional$$, $$Fix a broken token-bucket rate limiter$$, $$This token-bucket rate limiter uses a virtual clock (elapsed seconds passed explicitly). It has an off-by-one bug that denies a request that should be allowed. Fix it.$$, $${"code": "class TokenBucket:\n    def __init__(self, rate, capacity):\n        self.rate = rate\n        self.capacity = capacity\n        self.tokens = capacity\n\n    def allow(self, elapsed):\n        self.tokens = min(self.capacity, self.tokens + elapsed * self.rate)\n        if self.tokens > 1:\n            self.tokens -= 1\n            return True\n        return False\n"}$$::jsonb, null, null, $$[{"input": {"capacity": 1, "rate": 1, "calls": [0]}, "expected": [true]}, {"input": {"capacity": 2, "rate": 1, "calls": [0, 0]}, "expected": [true, true]}]$$::jsonb, $$medium$$),
  ($$tooluse$$, $$debugging$$, $$functional$$, $$Fix a broken retry-with-backoff decorator$$, $$This retry decorator allows one extra attempt beyond max_retries due to an off-by-one in the loop condition. Fix it so exactly max_retries total attempts are made before raising.$$, $${"code": "def retry(max_retries):\n    def decorator(fn):\n        def wrapper(*args, **kwargs):\n            attempt = 0\n            last_exc = None\n            while attempt <= max_retries:\n                try:\n                    return fn(*args, **kwargs)\n                except Exception as e:\n                    last_exc = e\n                    attempt += 1\n            raise last_exc\n        return wrapper\n    return decorator\n"}$$::jsonb, null, null, $$[{"input": {"max_retries": 3, "always_fail": true}, "expected": {"raised": true, "attempts": 3}}]$$::jsonb, $$medium$$),
  ($$tooluse$$, $$workflow$$, $$multi-turn$$, $$Iteratively correct a malformed tool call across rounds of feedback$$, $$Given an initial malformed tool call and 3 rounds of feedback, converge on the correct, fully-specified tool call.$$, $${"initial_call": {"tool": "get_wather", "args": {"city": "Paris"}}, "rounds": 3}$$::jsonb, $${"tool": "get_weather", "args": {"city": "Paris", "country": "FR"}}$$::jsonb, null, null, $$expert$$),
  ($$reasonbench$$, $$logic$$, $$exact$$, $$Identify the only odd number in a list$$, $$Given a list of integers, identify the single odd number among otherwise-even numbers.$$, $${"numbers": [14, 22, 9, 36, 8]}$$::jsonb, $$"9"$$::jsonb, null, null, $$easy$$),
  ($$reasonbench$$, $$logic$$, $$exact$$, $$Solve a 3-house logic puzzle$$, $$There are 3 houses in a row, each a different color (red, green, blue) and each with a different pet (cat, dog, fish). Clues: (1) The red house owner has a dog. (2) The green house is immediately left of the blue house. (3) The house with the fish is not green. (4) The blue house is not the third house. Which house number (1, 2, or 3) has the cat?$$, $${"clues": ["The red house owner has a dog.", "The green house is immediately left of the blue house.", "The house with the fish is not green.", "The blue house is not the third house."], "question": "Which house number has the cat?"}$$::jsonb, $$"1"$$::jsonb, null, null, $$hard$$),
  ($$reasonbench$$, $$sequences$$, $$exact$$, $$Determine the next number in a sequence$$, $$Given the sequence 2, 6, 12, 20, 30, determine the next number.$$, $${"sequence": [2, 6, 12, 20, 30]}$$::jsonb, $$"42"$$::jsonb, null, null, $$easy$$),
  ($$reasonbench$$, $$logic$$, $$exact$$, $$Evaluate a nested boolean expression$$, $$Evaluate the boolean expression: (True and not False) or (False and True)$$, $${"expression": "(True and not False) or (False and True)"}$$::jsonb, $$true$$::jsonb, null, null, $$easy$$),
  ($$reasonbench$$, $$logic$$, $$exact$$, $$Determine the winner of a Rock-Paper-Scissors-Lizard-Spock round$$, $$Given two moves in Rock-Paper-Scissors-Lizard-Spock, determine the winner. Lizard poisons Spock and eats Paper; Spock smashes Scissors and vaporizes Rock.$$, $${"player_a": "lizard", "player_b": "spock"}$$::jsonb, $$"player_a"$$::jsonb, null, null, $$medium$$),
  ($$reasonbench$$, $$data-processing$$, $$exact$$, $$Compute the result of a base-conversion chain$$, $$Convert the given binary value to decimal, then to lowercase hexadecimal.$$, $${"value": "1010", "from_base": 2, "steps": ["to_decimal", "to_hex"]}$$::jsonb, $$"a"$$::jsonb, null, null, $$medium$$),
  ($$reasonbench$$, $$orchestration$$, $$structural$$, $$Decompose a compound question, then answer each part in order$$, $$Given a compound question, first decompose it into sub-questions, then answer them in order.$$, $${"question": "What is the capital of France, and what is its population?", "steps": ["decompose", "answer"]}$$::jsonb, $${"tool_calls": ["decompose", "answer"]}$$::jsonb, null, null, $$medium$$),
  ($$reasonbench$$, $$critical-thinking$$, $$semantic$$, $$Explain the logical flaw in a given syllogism$$, $$Identify what is actually wrong with the following syllogism: 'All birds can fly. Penguins are birds. Therefore, penguins can fly.'$$, $${"syllogism": "All birds can fly. Penguins are birds. Therefore, penguins can fly."}$$::jsonb, null, $$Full credit if the response identifies that the flaw is a false premise (not all birds can fly, e.g. penguins, ostriches) rather than a structural or logical error, since the syllogism's form is actually valid. Deduct credit if the response claims the logical form itself is invalid.$$, null, $$hard$$),
  ($$reasonbench$$, $$math$$, $$multi-turn$$, $$Solve a math word problem, revising the answer across rounds of hints$$, $$A train travels 60 miles in 45 minutes. At this rate, how far does it travel in 2 hours? Converge on the correct answer across 3 rounds of hints.$$, $${"problem": "A train travels 60 miles in 45 minutes. At this rate, how far does it travel in 2 hours?", "rounds": 3}$$::jsonb, $$"160"$$::jsonb, null, null, $$medium$$),
  ($$reasonbench$$, $$math$$, $$multi-turn$$, $$Correct a flawed chain-of-thought across rounds of feedback$$, $$Given a flawed initial probability calculation and 3 rounds of corrective feedback, converge on the correct probability.$$, $${"problem": "Probability of exactly 2 heads in 3 fair coin flips.", "initial_reasoning": "Since there are 2 outcomes and we want 2 heads, probability is 2/3.", "rounds": 3}$$::jsonb, $$"0.375"$$::jsonb, null, null, $$expert$$),
  ($$agentops$$, $$scheduling$$, $$functional$$, $$Fix a broken next-run-time calculator for a periodic job$$, $$This function computes the next minute (0-59) a job runs, given it runs every `interval` minutes. It incorrectly returns the current slot instead of the next one. Fix it.$$, $${"code": "def next_run_minutes(current_minute, interval):\n    return (current_minute // interval) * interval\n"}$$::jsonb, null, null, $$[{"input": {"current_minute": 7, "interval": 15}, "expected": 15}, {"input": {"current_minute": 0, "interval": 10}, "expected": 10}, {"input": {"current_minute": 50, "interval": 15}, "expected": 0}]$$::jsonb, $$medium$$),
  ($$agentops$$, $$reliability$$, $$functional$$, $$Fix a broken exponential-backoff scheduler that never resets$$, $$This backoff scheduler's reset() does not clear the attempt counter, so delays keep growing even after a success. Fix it.$$, $${"code": "class Backoff:\n    def __init__(self, base=1, max_delay=100):\n        self.base = base\n        self.max_delay = max_delay\n        self.attempt = 0\n\n    def next_delay(self):\n        delay = min(self.base * (2 ** self.attempt), self.max_delay)\n        self.attempt += 1\n        return delay\n\n    def reset(self):\n        pass\n"}$$::jsonb, null, null, $$[{"input": {"base": 1, "max_delay": 100, "calls": ["next_delay", "next_delay", "reset", "next_delay"]}, "expected": [1, 2, 1]}]$$::jsonb, $$medium$$),
  ($$agentops$$, $$reliability$$, $$functional$$, $$Fix a broken bounded webhook deduplication buffer$$, $$This deduplicator should only remember the most recent `capacity` event IDs, evicting the oldest first. It never evicts, so old IDs are incorrectly still flagged as duplicates forever. Fix it.$$, $${"code": "class Deduper:\n    def __init__(self, capacity):\n        self.capacity = capacity\n        self.seen = []\n\n    def is_duplicate(self, event_id):\n        if event_id in self.seen:\n            return True\n        self.seen.append(event_id)\n        if len(self.seen) > self.capacity:\n            self.seen.append(None)\n        return False\n"}$$::jsonb, null, null, $$[{"input": {"capacity": 2, "ids": ["a", "b", "c", "a"]}, "expected": [false, false, false, false]}]$$::jsonb, $$hard$$),
  ($$agentops$$, $$reliability$$, $$functional$$, $$Fix a file lock that isn't released on exception$$, $$This lock helper fails to release the lock if the wrapped function raises. Fix it so the lock is always released.$$, $${"code": "class FileLock:\n    def __init__(self):\n        self.locked = False\n\n    def acquire(self):\n        self.locked = True\n\n    def release(self):\n        self.locked = False\n\n    def run_with_lock(self, fn):\n        self.acquire()\n        result = fn()\n        self.release()\n        return result\n"}$$::jsonb, null, null, $$[{"input": {"should_raise": true}, "expected": {"locked_after": false, "raised": true}}, {"input": {"should_raise": false}, "expected": {"locked_after": false, "raised": false}}]$$::jsonb, $$medium$$),
  ($$agentops$$, $$reliability$$, $$functional$$, $$Fix a broken log-rotation size threshold calculator$$, $$This function decides whether to rotate a log file based on max size in megabytes, but uses the wrong byte multiplier. Fix it.$$, $${"code": "def should_rotate(current_size_bytes, max_size_mb):\n    max_bytes = max_size_mb * 1000\n    return current_size_bytes >= max_bytes\n"}$$::jsonb, null, null, $$[{"input": {"current_size_bytes": 1048576, "max_size_mb": 1}, "expected": true}, {"input": {"current_size_bytes": 500000, "max_size_mb": 1}, "expected": false}]$$::jsonb, $$easy$$),
  ($$agentops$$, $$reliability$$, $$functional$$, $$Fix a broken task-queue deduplication key generator$$, $$This function should produce identical dedup keys for logically-identical tasks regardless of field order, but doesn't. Fix it.$$, $${"code": "import json\n\ndef dedup_key(task):\n    return json.dumps(task)\n"}$$::jsonb, null, null, $$[{"input": {"task_a": {"type": "email", "to": "x@example.com"}, "task_b": {"to": "x@example.com", "type": "email"}}, "expected": true}]$$::jsonb, $$medium$$),
  ($$agentops$$, $$incident-response$$, $$semantic$$, $$Evaluate whether an incident postmortem addresses root cause$$, $$Assess whether the following postmortem addresses the true root cause of the outage: 'The outage was caused by a null pointer exception in the billing service. We fixed it by adding a null check at line 482 and redeployed.'$$, $${"postmortem": "The outage was caused by a null pointer exception in the billing service. We fixed it by adding a null check at line 482 and redeployed."}$$::jsonb, null, $$Full credit if the response notes the postmortem only patches the symptom (a missing null check) without addressing why the null value reached that code path (e.g. missing upstream validation, no schema enforcement), i.e. it lacks a true root-cause fix and follow-up action items. Deduct credit if the response accepts the postmortem as sufficient.$$, null, $$hard$$),
  ($$agentops$$, $$incident-response$$, $$semantic$$, $$Assess whether a runbook step order is operationally safe$$, $$Assess whether the step order in this runbook is safe: '1. Delete the old database snapshot. 2. Take a new database snapshot. 3. Deploy the migration. 4. Verify the migration succeeded.'$$, $${"runbook": "1. Delete the old database snapshot. 2. Take a new database snapshot. 3. Deploy the migration. 4. Verify the migration succeeded."}$$::jsonb, null, $$Full credit if the response identifies that deleting the old snapshot before confirming the new one exists removes the rollback safety net and is unsafe; the correct order takes the new snapshot first, verifies it, then deletes the old one only after the migration is confirmed successful. Deduct credit if the response does not flag the ordering hazard.$$, null, $$medium$$),
  ($$agentops$$, $$workflow$$, $$multi-turn$$, $$Iteratively refine a deployment rollback script across rounds of review feedback$$, $$Given an initial rollback script and 3 rounds of code review feedback, converge on a safe, verifiable rollback script.$$, $${"initial_script": "kubectl rollout undo deployment/api", "rounds": 3}$$::jsonb, $${"script": "kubectl rollout undo deployment/api --to-revision=<n> && kubectl rollout status deployment/api"}$$::jsonb, null, null, $$expert$$),
  ($$agentops$$, $$workflow$$, $$multi-turn$$, $$Converge on a correct on-call escalation policy across rounds of stakeholder feedback$$, $$Given an initial escalation policy and 3 rounds of stakeholder feedback, converge on a policy with severity tiers and secondary escalation.$$, $${"initial_policy": "Page the on-call engineer immediately for any alert.", "rounds": 3}$$::jsonb, $${"policy": "Page on-call immediately for Sev1/Sev2 alerts; batch Sev3 alerts for business hours; escalate to secondary on-call after 10 minutes without acknowledgment."}$$::jsonb, null, null, $$expert$$);
