-- Backfill expected_output (reference fix) for the 15 functional tasks from 0008.
update benchmark_tasks set expected_output = $${"reference_fix": "def validate_iban(iban):\n    iban = iban.replace(' ', '').upper()\n    rearranged = iban[4:] + iban[:4]\n    digits = ''\n    for ch in rearranged:\n        if ch.isdigit():\n            digits += ch\n        else:\n            digits += str(ord(ch) - ord('A') + 10)\n    return int(digits) % 97 == 1\n"}$$::jsonb where title = $$Fix a broken IBAN validator$$;
update benchmark_tasks set expected_output = $${"reference_fix": "def is_balanced(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for ch in s:\n        if ch in '([{':\n            stack.append(ch)\n        elif ch in ')]}':\n            if not stack:\n                return False\n            top = stack.pop()\n            if top != pairs[ch]:\n                return False\n    return len(stack) == 0\n"}$$::jsonb where title = $$Repair a stack-based balanced-brackets checker$$;
update benchmark_tasks set expected_output = $${"reference_fix": "def max_window_sum(nums, k):\n    n = len(nums)\n    if k > n:\n        return None\n    window_sum = sum(nums[:k])\n    best = window_sum\n    for i in range(k, n):\n        window_sum += nums[i] - nums[i - k]\n        best = max(best, window_sum)\n    return best\n"}$$::jsonb where title = $$Correct an off-by-one in a sliding-window maximum-sum function$$;
update benchmark_tasks set expected_output = $${"reference_fix": "def partition(arr, low, high):\n    pivot = arr[high]\n    i = low - 1\n    for j in range(low, high):\n        if arr[j] <= pivot:\n            i += 1\n            arr[i], arr[j] = arr[j], arr[i]\n    arr[i + 1], arr[high] = arr[high], arr[i + 1]\n    return i + 1\n\ndef quicksort(arr, low=0, high=None):\n    if high is None:\n        high = len(arr) - 1\n    if low < high:\n        p = partition(arr, low, high)\n        quicksort(arr, low, p - 1)\n        quicksort(arr, p + 1, high)\n    return arr\n"}$$::jsonb where title = $$Fix a broken quicksort partition step$$;
update benchmark_tasks set expected_output = $${"reference_fix": "class Node:\n    def __init__(self, val):\n        self.val = val\n        self.prev = None\n        self.next = None\n\ndef remove_node(node):\n    if node.prev:\n        node.prev.next = node.next\n    if node.next:\n        node.next.prev = node.prev\n"}$$::jsonb where title = $$Fix a broken doubly linked list node removal$$;
update benchmark_tasks set expected_output = $${"reference_fix": "def flatten(d, parent_key='', sep='.'):\n    items = {}\n    for k, v in d.items():\n        new_key = f'{parent_key}{sep}{k}' if parent_key else k\n        if isinstance(v, dict):\n            items.update(flatten(v, new_key, sep=sep))\n        else:\n            items[new_key] = v\n    return items\n"}$$::jsonb where title = $$Fix a broken nested-dict flattening function$$;
update benchmark_tasks set expected_output = $${"reference_fix": "from collections import OrderedDict\n\nclass LRUCache:\n    def __init__(self, capacity):\n        self.capacity = capacity\n        self.cache = OrderedDict()\n\n    def get(self, key):\n        if key not in self.cache:\n            return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n\n    def put(self, key, value):\n        if key in self.cache:\n            del self.cache[key]\n        elif len(self.cache) >= self.capacity:\n            self.cache.popitem(last=False)\n        self.cache[key] = value\n"}$$::jsonb where title = $$Fix a broken LRU cache eviction order$$;
update benchmark_tasks set expected_output = $${"reference_fix": "class TokenBucket:\n    def __init__(self, rate, capacity):\n        self.rate = rate\n        self.capacity = capacity\n        self.tokens = capacity\n\n    def allow(self, elapsed):\n        self.tokens = min(self.capacity, self.tokens + elapsed * self.rate)\n        if self.tokens >= 1:\n            self.tokens -= 1\n            return True\n        return False\n"}$$::jsonb where title = $$Fix a broken token-bucket rate limiter$$;
update benchmark_tasks set expected_output = $${"reference_fix": "def retry(max_retries):\n    def decorator(fn):\n        def wrapper(*args, **kwargs):\n            attempt = 0\n            last_exc = None\n            while attempt < max_retries:\n                try:\n                    return fn(*args, **kwargs)\n                except Exception as e:\n                    last_exc = e\n                    attempt += 1\n            raise last_exc\n        return wrapper\n    return decorator\n"}$$::jsonb where title = $$Fix a broken retry-with-backoff decorator$$;
update benchmark_tasks set expected_output = $${"reference_fix": "def next_run_minutes(current_minute, interval):\n    return ((current_minute // interval) + 1) * interval % 60\n"}$$::jsonb where title = $$Fix a broken next-run-time calculator for a periodic job$$;
update benchmark_tasks set expected_output = $${"reference_fix": "class Backoff:\n    def __init__(self, base=1, max_delay=100):\n        self.base = base\n        self.max_delay = max_delay\n        self.attempt = 0\n\n    def next_delay(self):\n        delay = min(self.base * (2 ** self.attempt), self.max_delay)\n        self.attempt += 1\n        return delay\n\n    def reset(self):\n        self.attempt = 0\n"}$$::jsonb where title = $$Fix a broken exponential-backoff scheduler that never resets$$;
update benchmark_tasks set expected_output = $${"reference_fix": "class Deduper:\n    def __init__(self, capacity):\n        self.capacity = capacity\n        self.seen = []\n\n    def is_duplicate(self, event_id):\n        if event_id in self.seen:\n            return True\n        self.seen.append(event_id)\n        if len(self.seen) > self.capacity:\n            self.seen.pop(0)\n        return False\n"}$$::jsonb where title = $$Fix a broken bounded webhook deduplication buffer$$;
update benchmark_tasks set expected_output = $${"reference_fix": "class FileLock:\n    def __init__(self):\n        self.locked = False\n\n    def acquire(self):\n        self.locked = True\n\n    def release(self):\n        self.locked = False\n\n    def run_with_lock(self, fn):\n        self.acquire()\n        try:\n            return fn()\n        finally:\n            self.release()\n"}$$::jsonb where title = $$Fix a file lock that isn't released on exception$$;
update benchmark_tasks set expected_output = $${"reference_fix": "def should_rotate(current_size_bytes, max_size_mb):\n    max_bytes = max_size_mb * 1024 * 1024\n    return current_size_bytes >= max_bytes\n"}$$::jsonb where title = $$Fix a broken log-rotation size threshold calculator$$;
update benchmark_tasks set expected_output = $${"reference_fix": "import json\n\ndef dedup_key(task):\n    return json.dumps(task, sort_keys=True)\n"}$$::jsonb where title = $$Fix a broken task-queue deduplication key generator$$;
